Repository gachimind/frontend, pull requests merged in 2023-01, with the labels that each got.

#11 FEAT: socket 통신을 통한 GameRoom 생성/입장/퇴장 주기에 대한 기능을 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/game/CamList.tsx
  src/components/game/ChatLog.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/RoomList.tsx
  src/components/home/UserInfo.tsx
  src/constants/socket.ts
  src/hooks/socket/socketInstance.ts
  src/hooks/socket/useAuthSocket.ts
  src/hooks/socket/useChatSocket.ts
  src/hooks/socket/useGameSocket.ts
  src/pages/Main.tsx
  src/pages/Room.tsx
  src/redux/modules/gameRoomSlice.ts
  src/redux/modules/userSlice.tsx
  src/redux/store.ts
  src/types/chatType.ts
  src/types/gameRoomType.ts
  src/types/userType.ts
Labels: :bulb: remind

#19 FEAT: 대략적인 페이지별 컴포넌트 위치 추가
  public/index.html
  src/components/common/Layout.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/pages/Room.tsx
Labels: :rabbit: frontend

#25 FEAT: 메인 페이지, 게임 페이지 UI 초안
  public/index.html
  src/App.tsx
  src/assets/camIcon.svg
  src/assets/circleIcon.svg
  src/assets/headerIcon.svg
  src/assets/micIcon.svg
  src/assets/micOnCamIcon.svg
  src/assets/ruleIcon.svg
  src/assets/scoreBoard.svg
  src/components/common/Layout.tsx
  src/components/game/CamButton.tsx
  src/components/game/ChatLog.tsx
  src/components/game/MicButton.tsx
  src/components/game/Presenter.tsx
  src/components/game/ScoreBoard.tsx
  src/components/home/RoomList.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/Container.tsx
  src/components/layout/ContentBox.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/main/MainLayout.tsx
  src/components/layout/mypage/MyPageLayout.tsx
  src/components/layout/room/RoomLayout.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/pages/Room.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  styled-components.d.ts
  tsconfig.json
Labels: :rabbit: frontend

#28 FEAT: 마이페이지, 로그인 모달창, 방 생성 모달창 와이어프레임 기반 UI 구현
  src/assets/closeButton.svg
  src/components/common/Modal.tsx
  src/components/game/CamButton.tsx
  src/components/game/MicButton.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/LoginModal.tsx
  src/components/layout/main/MainLayout.tsx
  src/components/mypage/Keyword.tsx
  src/pages/Mypage.tsx
Labels: :rabbit: frontend

#32 REFACTOR: UI 관련 코드 리팩터
  src/apis/instance.ts
  src/apis/userApi.ts
  src/assets/scoreBoard.svg
  src/assets/svg_camButtonIcon.svg
  src/assets/svg_closeModalIcon.svg
  src/assets/svg_gameRuleIcon.svg
  src/assets/svg_imageHolderIcon.svg
  src/assets/svg_micButtonIcon.svg
  src/assets/svg_micOnIcon.svg
  src/assets/svg_slideLeftIcon.svg
  src/assets/svg_slideRightIcon.svg
  src/assets/svg_threeLightsIcon.svg
  src/components/common/Modal.tsx
  src/components/game/Cam.tsx
  src/components/game/CamButton.tsx
  src/components/game/CamList.tsx
  src/components/game/CamListSliderArrow.tsx
  src/components/game/ChatLog.tsx
  src/components/game/MicButton.tsx
  src/components/game/Presenter.tsx
  src/components/game/ScoreBoard.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/LoginModal.tsx
  src/components/home/RoomList.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/ContentBox.tsx
  src/components/layout/ContentContainer.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainTemplate.tsx
  src/components/layout/MyPageTemplate.tsx
  src/components/layout/PageContainer.tsx
  src/components/layout/RoomTemplate.tsx
  src/components/mypage/Keyword.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/pages/Room.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: :rabbit: frontend

#39 FIX: 식별된 사소한 오류 사전에 수정하기
  src/components/common/Modal.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/RoomList.tsx
  src/hooks/useLocalStream.ts
  src/pages/Room.tsx
  src/redux/modules/userSlice.ts
Labels: :warning: fix

#44 FIX: 게임페이지 툴팁 모달창 위치 수정하기
  src/components/common/Selection.tsx
  src/components/game/GameRuleToolTip.tsx
  src/components/layout/RoomTemplate.tsx
Labels: :rabbit: frontend, :warning: fix

#47 FEAT: 게임방 출입 비밀번호 처리 및 관련 예외상황 처리하기
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Input.tsx
  src/components/common/InputContainer.tsx
  src/components/common/ToastProvider.tsx
  src/components/game/GameReady.tsx
  src/components/game/GameStart.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/ReportBugModal.tsx
  src/components/home/RoomList.tsx
  src/components/layout/MainTemplate.tsx
  src/hooks/socket/useErrorSocket.ts
  src/hooks/socket/useGameInitiationSocket.ts
  src/hooks/socket/useGameSocket.ts
  src/hooks/socket/useGameUpdateSocket.ts
  src/pages/Main.tsx
  src/pages/Room.tsx
  src/redux/modules/gameRoomSlice.ts
  src/redux/modules/userSlice.ts
  src/types/gameRoomType.ts
  src/types/socketType.ts
  src/utils/stroage.ts
  src/utils/toast.ts
Labels: :computer: 기능

#46 FEAT: 소셜 로그인 기능 구현
  package-lock.json
  package.json
  server/authenticationHandler.js
  server/index.js
  src/App.tsx
  src/apis/instance.ts
  src/components/common/LoginStatus.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/LoginModal.tsx
  src/components/home/ReportBugModal.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainTemplate.tsx
  src/components/layout/RoomTemplate.tsx
  src/components/mypage/EditProfileModal.tsx
  src/hooks/socket/socketInstance.ts
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/redux/modules/userSlice.ts
  src/shared/Router.tsx
  src/utils/getCookie.ts
Labels: :rabbit: frontend, :computer: 기능

#53 FEAT: 메인페이지, 게임페이지 UI 디자인 반영
  src/App.tsx
  src/app.css
  src/assets/svg_bugIcon.svg
  src/assets/svg_camButtonIcon.svg
  src/assets/svg_closeModalIcon.svg
  src/assets/svg_gameRuleIcon.svg
  src/assets/svg_leaveRoomIcon.svg
  src/assets/svg_lockIcon.svg
  src/assets/svg_medalIcon.svg
  src/assets/svg_micButtonIcon.svg
  src/assets/svg_micOnIcon.svg
  src/assets/svg_readyButton.svg
  src/assets/svg_roomCard.svg
  src/assets/svg_selectIcon.svg
  src/assets/svg_startButton.svg
  src/assets/svg_trophyIcon.svg
  src/assets/ttf_joystick.ttf
  src/assets/ttf_neodgm.ttf
  src/components/common/Input.tsx
  src/components/common/InputContainer.tsx
  src/components/common/Modal.tsx
  src/components/common/Selection.tsx
  src/components/game/CamButton.tsx
  src/components/game/ChatLog.tsx
  src/components/game/GameReady.tsx
  src/components/game/GameRuleToolTip.tsx
  src/components/game/GameStart.tsx
  src/components/game/MicButton.tsx
  src/components/game/Presenter.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/LoginModal.tsx
  src/components/home/ReportBugModal.tsx
  src/components/home/RoomList.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/ContentContainer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainTemplate.tsx
  src/components/layout/PageContainer.tsx
  src/components/layout/RoomTemplate.tsx
  src/components/mypage/EditProfileModal.tsx
  src/pages/Room.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  styled-components.d.ts
Labels: :cake: UI

#51 FEAT: 비밀번호 입력 관련 흐름 처리 완성하기
  src/apis/instance.ts
  src/components/common/LoginStatus.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/RoomList.tsx
  src/constants/socket.ts
  src/hooks/socket/useAuthSocket.ts
  src/hooks/socket/useErrorSocket.ts
  src/hooks/socket/useGameSocket.ts
  src/pages/Main.tsx
  src/pages/Room.tsx
  src/redux/modules/userSlice.ts
Labels: :computer: 기능

#71 REFACTOR: 메인 페이지, 게임 페이지 UI 공통 컴포넌트 분리
  src/assets/svg_camButtonIcon.svg
  src/assets/svg_camButtonOffIcon.svg
  src/assets/svg_camButtonOnIcon.svg
  src/assets/svg_gameRuleIcon.svg
  src/assets/svg_lockIcon.svg
  src/assets/svg_medalIcon.svg
  src/assets/svg_micButtonIcon.svg
  src/assets/svg_micButtonOffIcon.svg
  src/assets/svg_micButtonOnIcon.svg
  src/assets/svg_readyButton.svg
  src/assets/svg_smallMicOffIcon.svg
  src/assets/svg_smallMicOnIcon.svg
  src/assets/svg_startButton.svg
  src/assets/svg_trophyIcon.svg
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/LoginStatus.tsx
  src/components/common/Modal.tsx
  src/components/common/Selection.tsx
  src/components/game/CamButton.tsx
  src/components/game/GameReady.tsx
  src/components/game/GameResultModal.tsx
  src/components/game/GameStart.tsx
  src/components/game/MicButton.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/LoginModal.tsx
  src/components/home/ReportBugModal.tsx
  src/components/home/RoomList.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/MainTemplate.tsx
  src/components/layout/RoomTemplate.tsx
  src/components/mypage/EditProfileModal.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/redux/modules/userSlice.ts
  src/styles/theme.ts
Labels: :cake: UI, :warning: fix

#74 FEAT: 게임 시작 시 통신 구현하기
  src/components/common/GameButton.tsx
  src/components/game/Cam.tsx
  src/components/game/CamList.tsx
  src/components/game/CamStatus.tsx
  src/components/game/CamUserStatus.tsx
  src/components/game/GameReady.tsx
  src/components/game/GameStart.tsx
  src/components/game/PlayerImageHolder.tsx
  src/components/game/PresentationInfo.tsx
  src/components/game/Presenter.tsx
  src/components/game/PresenterCam.tsx
  src/components/game/Timer.tsx
  src/components/home/CreateGameModal.tsx
  src/constants/socket.ts
  src/hooks/socket/useGamePlaySocket.ts
  src/hooks/useGameTimeCountDown.ts
  src/pages/Room.tsx
  src/redux/modules/gamePlaySlice.ts
  src/redux/modules/gameRoomSlice.ts
  src/redux/store.ts
  src/types/socketType.ts
  src/utils/common.ts
Labels: :cake: UI, :computer: 기능

#73 FEAT: 메인페이지 대기방 목록 페이지네이션
  src/assets/svg_roomCard.svg
  src/components/home/RoomCard.tsx
  src/components/home/RoomList.tsx
  src/styles/theme.ts
Labels: :cake: UI

#78 FEAT: 게임만들기 입력 제한/글자 수 잘리는 부분 애니메이션 추가
  src/components/game/CamUserStatus.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/RoomCard.tsx
  src/components/home/RoomList.tsx
  src/components/home/UserInfo.tsx
  src/constants/options.ts
Labels: :cake: UI

#79 FEAT: 게임 종료 시 로직, UI처리 추가
  src/components/game/GameReady.tsx
  src/components/game/GameResultModal.tsx
  src/components/game/Presenter.tsx
  src/hooks/socket/useGamePlaySocket.ts
  src/hooks/useGameTimeCountDown.ts
  src/redux/modules/gamePlaySlice.ts
Labels: :computer: 기능

#83 FEAT: 추가된 디자인 UI 반영
  src/components/common/Selection.tsx
  src/components/game/GameResultModal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/ReportBugModal.tsx
  src/components/mypage/EditProfileModal.tsx
  src/components/mypage/Keyword.tsx
  src/constants/options.ts
Labels: :cake: UI

#89 FEAT: 게임 결과 그래프에 스코어 반영 및 캠 관련 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/game/CamUserStatus.tsx
  src/components/game/GameResultModal.tsx
  src/components/game/Presenter.tsx
  src/components/game/PresenterCam.tsx
  src/hooks/socket/useGamePlaySocket.ts
  src/redux/modules/gameRoomSlice.ts
  src/types/gameRoomType.ts
  src/utils/common.ts
Labels: :cake: UI

#91 TEST: 스토리북 세팅하기
  .github/workflows/pr.yml
  .storybook/main.js
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/common/Modal.tsx
  src/components/game/GameResultModal.tsx
  src/components/layout/PageContainer.tsx
  src/stories/common/modal.stories.tsx
  src/stories/game/GameResultModal.stories.tsx
Labels: :test_tube: test

#97 FEAT: 게임 나가기 확인 모달 추가 및 참여자 캠 닉네임 애니메이션 수정
  src/components/game/CamUserStatus.tsx
  src/components/game/LeaveRoomModal.tsx
  src/components/layout/RoomTemplate.tsx
Labels: :cake: UI, :warning: fix

#100 FEAT: 게임 중 Discussion Time에 발표자를 평가하는 기능과 UI를 추가
  src/components/game/ChatLog.tsx
  src/constants/socket.ts
  src/hooks/socket/useChatSocket.ts
  src/redux/modules/gamePlaySlice.ts
Labels: :computer: 기능

#102 FEAT: 게임 페이지에서의 새로고침/뒤로가기 처리
  src/components/home/EnterPrivateRoomModal.tsx
  src/hooks/useBeforeUnload.ts
  src/hooks/usePopState.ts
  src/pages/Room.tsx
Labels: :computer: 기능

#105 FIX: 자잘한 수정 및 리팩터링
  .github/workflows/pr.yml
  src/components/common/AxisXOverflowedText.tsx
  src/components/game/Cam.tsx
  src/components/game/CamUserStatus.tsx
  src/components/game/PresenterCam.tsx
  src/components/home/RoomCard.tsx
  src/stories/common/AxisXOverflowedText.stories.tsx
  src/stories/game/Cam.stories.tsx
  src/stories/home/RoomCard.stories.tsx
Labels: :cake: UI, :test_tube: test

#99 FEAT: 회원키워드 조회 json-server 업데이트 및 클라이언트 회원정보 조회 기능 수정, 회원키워드 조회 기능 추가
  server/index.js
  src/apis/userApi.ts
  src/components/home/UserInfo.tsx
  src/components/mypage/Keyword.tsx
  src/redux/modules/userSlice.ts
  src/types/userType.ts
Labels: :computer: 기능

#109 FIX: 게임 종료 후 처리에서 발생하는 문제 처리
  src/components/game/GameReady.tsx
  src/components/game/GameResultModal.tsx
  src/components/game/Presenter.tsx
  src/hooks/socket/useGameUpdateSocket.ts
  src/pages/Room.tsx
  src/redux/modules/gameRoomSlice.ts
Labels: :computer: 기능, :warning: fix

#111 FEAT: TURN서버 구현 #101
  .github/workflows/prod.yml
  src/hooks/useWebRTC.ts
Labels: :computer: 기능, :warning: fix

#107 FEAT: 야옹이 추가
  src/components/character/Cat.tsx
  src/components/character/CatEars.tsx
  src/components/character/CatStar.tsx
  src/components/character/Rocket.tsx
  src/constants/characters.ts
  src/stories/character/Cat.stories.tsx
Labels: :cake: UI

#115 FEAT: 게임 페이지 스코어보드 구성하기
  src/assets/img_scoreLarge.png
  src/assets/img_scoreSmall.png
  src/components/character/Cat.tsx
  src/components/character/CatOnGame.tsx
  src/components/character/CatScore.tsx
  src/components/character/Rocket.tsx
  src/components/common/AxisXOverflowedText.tsx
  src/components/common/ShootingStars.tsx
  src/components/common/Star.tsx
  src/components/common/StarlightBackground.tsx
  src/components/common/StaticStar.tsx
  src/components/game/GameResultBarChart.tsx
  src/components/game/GameResultModal.tsx
  src/components/game/PlayerCat.tsx
  src/components/game/ScoreBoard.tsx
  src/components/home/RoomCard.tsx
  src/constants/characters.ts
  src/stories/character/Cat.stories.tsx
  src/stories/character/CatOnGame.stories.tsx
  src/stories/character/CatScore.stories.tsx
  src/stories/game/GameResultModal.stories.tsx
  src/stories/game/StarlightBackground.stories.tsx
  src/utils/character.ts
  src/utils/common.ts
Labels: :bulb: remind, :cake: UI, :computer: 기능
