Repository gachimind/frontend, pull requests merged in 2023-02, with the labels that each got.

#118 FEAT: 로딩 화면 UI 반영
  src/components/character/CatEars.tsx
  src/components/character/CatStar.tsx
  src/components/character/GliteringStar.tsx
  src/components/character/LoadingCat.tsx
  src/components/character/ShootingStars.tsx
  src/components/character/Star.tsx
  src/components/character/StaticStar.tsx
  src/components/common/GlobalLoading.tsx
  src/components/common/GlobalLoadingBackground.tsx
  src/components/common/StarlightBackground.tsx
  src/components/common/TitleText.tsx
  src/stories/character/GliteringStar.stories.tsx
  src/stories/character/LoadingCat.stories.tsx
  src/stories/common/GlobalLoading.stories.tsx
  src/stories/common/TitleText.stories.tsx
Labels: :cake: UI

#114 FEAT: 수정 디자인 및 새로운 디자인 UI + 관련 기능 반영
  server/authenticationHandler.js
  server/index.js
  src/apis/instance.ts
  src/apis/userApi.ts
  src/assets/png_blackCatFaceImage.png
  src/assets/png_blueRocketImage.png
  src/assets/png_brownCatFaceImage.png
  src/assets/png_googleLoginButtonImage.png
  src/assets/png_grayCatFaceImage.png
  src/assets/png_kakaoIcon.png
  src/assets/png_logoIcon.png
  src/assets/png_mixCatFaceImage.png
  src/assets/png_orangeCatFaceImage.png
  src/assets/png_redRocketImage.png
  src/assets/png_whiteCatFaceImage.png
  src/assets/png_yellowRocketImage.png
  src/assets/svg_cursorIcon.svg
  src/assets/svg_footerImage.svg
  src/assets/svg_medalIcon.svg
  src/assets/svg_privateRoomIcon.svg
  src/assets/svg_roomListLeftIcon.svg
  src/assets/svg_roomListRightIcon.svg
  src/assets/svg_trophyIcon.svg
  src/components/character/Cat.tsx
  src/components/common/Button.tsx
  src/components/common/Modal.tsx
  src/components/common/Selection.tsx
  src/components/game/CamListSliderArrow.tsx
  src/components/game/GameRuleToolTip.tsx
  src/components/game/GameStart.tsx
  src/components/home/LoginModal.tsx
  src/components/home/LogoutModal.tsx
  src/components/home/ReportBugModal.tsx
  src/components/home/RoomCard.tsx
  src/components/home/RoomList.tsx
  src/components/home/SetUpInfo.tsx
  src/components/home/SetUpInfoModal.tsx
  src/components/home/SetUpInfoSuccess.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/ContentContainer.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainTemplate.tsx
  src/components/mypage/GrowthTower.tsx
  src/components/mypage/Keyword.tsx
  src/constants/options.ts
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/pages/Room.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  src/types/userType.ts
  src/utils/character.ts
Labels: :cake: UI, :computer: 기능

#125 FEAT: 닉네임 설정 공백 안되도록 설정
  src/components/home/SetUpInfo.tsx
Labels: :computer: 기능

#127 FEAT: 중복 로그인 처리 추가
  src/hooks/useDuplicatedUserInvalidate.ts
  src/pages/Main.tsx
  src/pages/Room.tsx
Labels: :computer: 기능

#129 FEAT: READY/START UI 개선
  src/components/common/GameButton.tsx
  src/components/game/GameReady.tsx
  src/components/game/GameStart.tsx
  src/components/game/Presenter.tsx
  src/components/layout/GameButtonContainer.tsx
  src/stories/common/GameButton.stories.tsx
  src/stories/game/GameReady.stories.tsx
Labels: :cake: UI

#132 FEAT: 사용자 점수에 맞춰 캣타워/고양이 보여주기 추가
  src/components/mypage/GrowthTower.tsx
Labels: :cake: UI

#140 FIX: 게임 규칙 모달 내용 설정
  src/components/game/GameRuleToolTip.tsx
Labels: :cake: UI

#134 FEAT: 회원정보 수정 기능 추가
  src/apis/userApi.ts
  src/components/home/SetUpInfo.tsx
  src/components/home/SetUpInfoModal.tsx
  src/components/home/UserInfo.tsx
  src/redux/modules/userSlice.ts
Labels: :computer: 기능

#136 FIX: 방 나가기 모달 UI 수정
  src/components/game/LeaveRoomModal.tsx
  src/components/mypage/EditProfileModal.tsx
  src/components/mypage/GrowthTower.tsx
Labels: :cake: UI

#138 FEAT: 마이페이지 로그아웃 모달
  src/components/common/Modal.tsx
  src/components/home/LogoutModal.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainTemplate.tsx
  src/components/layout/MyPageTemplate.tsx
  src/components/layout/RoomTemplate.tsx
Labels: :cake: UI, :computer: 기능

#130 FEAT: 버튼 이벤트 디자인 적용
  src/components/home/CreateGameModal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/SetUpInfo.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: :cake: UI

#142 FEAT: 캠 꺼졌을 때 UI 추가
  src/components/game/Cam.tsx
  src/components/game/CamList.tsx
  src/components/game/CamUserStatus.tsx
  src/components/game/Presenter.tsx
  src/components/game/PresenterCam.tsx
  src/hooks/useWebRTC.ts
Labels: :cake: UI

#147 FIX: 자잘한 UI 수정/추가
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/assets/svg_cursorIcon.svg
  src/assets/svg_instagramIcon.svg
  src/components/common/Button.tsx
  src/components/common/Modal.tsx
  src/components/home/EnterPrivateRoomModal.tsx
  src/components/home/LogoutModal.tsx
  src/components/layout/Footer.tsx
  src/components/layout/RoomTemplate.tsx
  src/styles/GlobalStyle.ts
Labels: :cake: UI

#148 FEAT: 애니메이션 컴포넌트 관련 수정
  src/components/character/CatOnGame.tsx
  src/components/character/CatScore.tsx
  src/components/character/ShootingStars.tsx
  src/components/character/Star.tsx
  src/components/common/StarlightBackground.tsx
Labels: :cake: UI

#149 FEAT: 탈주자 처리
  src/hooks/socket/socketInstance.ts
  src/hooks/socket/useErrorSocket.ts
  src/hooks/socket/useGameUpdateSocket.ts
  src/pages/Room.tsx
Labels: :computer: 기능

#154 FIX: 자잘한 오류 수정
  src/components/common/Modal.tsx
  src/components/game/GameRuleToolTip.tsx
  src/components/home/SetUpInfoModal.tsx
  src/components/home/SetUpInfoSuccess.tsx
Labels: :warning: fix

#155 FEAT: 게임 페이지 키워드/캠 목록 개선 및 기타 UI 수정
  src/components/common/GameButton.tsx
  src/components/common/ToastProvider.tsx
  src/components/game/CamButton.tsx
  src/components/game/CamList.tsx
  src/components/game/MicButton.tsx
  src/components/game/Presenter.tsx
  src/components/game/PresenterKeywordBox.tsx
  src/components/home/CreateGameModal.tsx
  src/components/home/LoginModal.tsx
  src/components/home/ReportBugModal.tsx
  src/constants/options.ts
  src/hooks/socket/useChatSocket.ts
  src/redux/modules/gamePlaySlice.ts
  src/redux/modules/playerMediaSlice.ts
  src/stories/game/PresenterKeywordBox.stories.tsx
  src/types/socketType.ts
  src/utils/common.ts
Labels: :cake: UI

#161 FEAT: 버그 제보 api 설정
  src/components/home/ReportBugModal.tsx
Labels: :cake: UI

#168 FIX: 자잘한 문제 수정
  src/components/home/ReportBugModal.tsx
  src/components/mypage/GrowthTower.tsx
Labels: :warning: fix

#169 FIX: 게임방 상태 변화에 따른 미디어스트림 on/off 동작 문제
  src/components/game/Cam.tsx
  src/components/game/CamList.tsx
  src/hooks/socket/useGameUpdateSocket.ts
  src/hooks/useWebRTC.ts
  src/pages/Room.tsx
  src/redux/modules/playerMediaSlice.ts
  src/redux/modules/userMediaSlice.ts
Labels: :fire: bug

#170 FIX: 스코어링 관련 문제 해결하기
  src/components/character/CatOnGame.tsx
  src/components/character/CatScore.tsx
  src/components/game/ChatLog.tsx
  src/components/game/GameResultBarChart.tsx
  src/components/game/PlayerCat.tsx
  src/stories/character/CatOnGame.stories.tsx
  src/stories/character/CatScore.stories.tsx
  src/stories/game/GameResultModal.stories.tsx
Labels: :warning: fix

#172 FEAT: 방 입장 시 기존 유저들의 캠 상태 반영 #171
  src/components/game/Cam.tsx
  src/components/game/CamList.tsx
Labels: :computer: 기능

#174 FIX: keydown 시 한글 조합중인지 검사 추가
  src/components/game/ChatLog.tsx
Labels: :warning: fix

#181 FEAT: 공지사항 모달 추가
  src/components/home/AnnouncementModal.tsx
  src/pages/Main.tsx
Labels: :cake: UI, :computer: 기능

#178 FIX: 게임방 나가기 클릭으로 나갈 경우 점수 반영 안되는 문제 수정
  src/components/game/LeaveRoomModal.tsx
Labels: :warning: fix

#188 FEAT: json server 업데이트
  server/index.js
Labels: :computer: 기능

#192 FIX: 비밀번호 0으로 시작할 경우를 위한 type 수정
  src/components/home/CreateGameModal.tsx
  src/hooks/socket/useGameSocket.ts
  src/redux/modules/gameRoomSlice.ts
  src/types/socketType.ts
  src/utils/stroage.ts
Labels: :warning: fix

#186 FIX: useState 변수명 수정, new Date() 컴포넌트에서 바로 하지 않도록 수정
  src/components/home/AnnouncementModal.tsx
  src/components/home/LoginModal.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/RoomTemplate.tsx
  src/pages/Main.tsx
Labels: :warning: fix

#193 FIX: 채팅 입력 UI오류 수정
  src/components/game/ChatLog.tsx
Labels: :cake: UI

#196 FIX: 게임 페이지 캠/마이크 관련 개선, 수정
  src/components/game/Cam.tsx
  src/components/game/CamList.tsx
  src/components/game/PlayerCat.tsx
  src/components/game/PresentationInfo.tsx
  src/components/game/Presenter.tsx
  src/hooks/useGameTimeCountDown.ts
  src/stories/game/Timer.stories.tsx
Labels: :warning: fix

#198 DOCS: 리드미 1차 작성
  README.md
Labels: documentation

#202 FEAT: 깃허브 OAuth로그인 추가
  src/assets/svg_githubicon.svg
  src/components/home/LoginModal.tsx
Labels: :computer: 기능

#200 FEAT: Player Cam status에 고양이 아이콘 추가
  src/components/character/CatIcon.tsx
  src/components/game/Cam.tsx
  src/components/game/CamUserStatus.tsx
  src/components/game/PlayerImageHolder.tsx
  src/stories/character/CatIcon.stories.tsx
Labels: :cake: UI

#204 FIX: 일부 UI적인 면 개선
  server/index.js
  src/assets/svg_homeIcon.svg
  src/assets/svg_myPageIcon.svg
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainTemplate.tsx
  src/components/layout/MyPageTemplate.tsx
Labels: :cake: UI, :computer: 기능

#211 FEAT: 캠 거울모드 적용
  src/components/game/Cam.tsx
Labels: :cake: UI

#214 FEAT: 키워드 링크 추가
  src/components/mypage/Keyword.tsx
  src/types/userType.ts
Labels: :cake: UI, :computer: 기능

#217 FEAT: 캣타워 말풍선 UI 추가
  src/assets/svg_leftSpeechBubble.svg
  src/assets/svg_rightSpeechBubble.svg
  src/components/mypage/GrowthTower.tsx
Labels: :cake: UI

#208 FEAT: RTK Query 도입
  server/index.js
  src/apis/instance.ts
  src/apis/userApi.ts
  src/components/common/LoginStatus.tsx
  src/components/game/CamList.tsx
  src/components/game/ChatLog.tsx
  src/components/game/Presenter.tsx
  src/components/home/LogoutModal.tsx
  src/components/home/RoomCard.tsx
  src/components/home/RoomList.tsx
  src/components/home/SetUpInfo.tsx
  src/components/home/SetUpInfoSuccess.tsx
  src/components/home/UserInfo.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mypage/GrowthTower.tsx
  src/components/mypage/Keyword.tsx
  src/hooks/socket/useAuthSocket.ts
  src/hooks/socket/useChatSocket.ts
  src/hooks/useDuplicatedUserInvalidate.ts
  src/pages/Main.tsx
  src/pages/Room.tsx
  src/redux/modules/userSlice.ts
  src/redux/query/coreApi.ts
  src/redux/query/user.ts
  src/redux/store.ts
  src/shared/Router.tsx
  src/stories/character/CatOnGame.stories.tsx
Labels: :computer: 기능

#224 FIX: 닉네임 길어질때 웰컴 모달 UI 수정
  src/components/home/SetUpInfoSuccess.tsx
Labels: :cake: UI, :warning: fix

#227 FEAT: 발표종료 후 토론시간에 하는 평가 시스템 개선
  package-lock.json
  package.json
  src/components/common/CircularProgress.tsx
  src/components/game/ChatLog.tsx
  src/components/game/PresentEvaluate.tsx
  src/components/game/Presenter.tsx
  src/components/game/RatingCats.tsx
  src/components/layout/GameButtonContainer.tsx
  src/hooks/socket/useGameInitiationSocket.ts
  src/hooks/useDraggable.ts
  src/stories/common/CircularProgress.stories.tsx
  src/stories/game/PresentEvaluate.stories.tsx
Labels: :cake: UI, :computer: 기능

#234 FEAT: 효과음/배경음 넣기
  audio.d.ts
  src/assets/sounds/background.mp3
  src/assets/sounds/button.wav
  src/assets/sounds/nyang.wav
  src/assets/sounds/rocket.mp3
  src/assets/sounds/tick.wav
  src/assets/svg_soundMuted.svg
  src/assets/svg_soundUnmuted.svg
  src/components/character/Rocket.tsx
  src/components/common/Button.tsx
  src/components/common/SoundEffectButton.tsx
  src/components/game/Presenter.tsx
  src/components/game/Timer.tsx
  src/components/layout/Footer.tsx
  src/components/layout/PageContainer.tsx
  src/components/layout/RoomTemplate.tsx
  src/hooks/useBackgroundSound.ts
  src/hooks/useSound.ts
  src/redux/modules/userMediaSlice.ts
  tsconfig.json
Labels: :computer: 기능

#239 FEAT: 없는 페이지에 대한 요청 처리하기
  src/shared/Router.tsx
Labels: enhancement

#242 FIX: 닉네임 수정 관련 누락된 동작 추가하기
  src/components/home/SetUpInfo.tsx
Labels: :warning: fix

#241 FIX: 공지 모달이 페이지 이동 시 다시 나오는 문제 처리하기
  src/components/home/AnnouncementModal.tsx
  src/components/home/SpecialNotificationModal.tsx
  src/hooks/useSpecialNotification.tsx
  src/pages/Main.tsx
  src/redux/modules/notificationSlice.ts
  src/redux/store.ts
Labels: enhancement, :warning: fix
